name: Lint and Test
on:
  push:
    branches: 
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0

  testCoverage:
    name: Test With Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: |
          go test -v -coverprofile=c.out ./...
          go tool cover -func=c.out
  
  testRaceDetector:
    name: Test With Race Detector
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v -race ./...
  

